### ISSUE TITLE
Fullstack tutorial does not start up

### ISSUE THREAD

**Issue by bwobst** [prisma/prisma-content-feedback#23]
**Describe the content issue**
[Step 3](https://www.prisma.io/tutorials/bootstrap-a-fullstack-graphql-app-with-react-and-apollo-cz12/) of the  fullstack tutorial says to run `yarn start` in `my-app/server`. Doing so results in the following:
```bash
Type "Node" is missing a "__resolveType" resolver. Pass false into "resolverValidationOptions.requireResolversForResolveType" to disable this warning.
Server is running on http://localhost:4000
```
In another terminal I start up the React app. The browser says the GraphQL server returns a 500 error. Below are the server logs are:
```bash
Error: Cannot use GraphQLSchema "[object GraphQLSchema]" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
    at instanceOf (/Users/brianwobst/code/my-app/server/node_modules/graphql/jsutils/instanceOf.js:15:13)
    at isSchema (/Users/brianwobst/code/my-app/server/node_modules/graphql/type/schema.js:52:35)
    at validateSchema (/Users/brianwobst/code/my-app/server/node_modules/graphql/type/validate.js:55:25)
    at assertValidSchema (/Users/brianwobst/code/my-app/server/node_modules/graphql/type/validate.js:80:16)
    at Object.validate (/Users/brianwobst/code/my-app/server/node_modules/graphql/validation/validate.js:57:35)
    at doRunQuery (/Users/brianwobst/code/my-app/server/node_modules/apollo-server-core/dist/runQuery.js:110:38)
    at /Users/brianwobst/code/my-app/server/node_modules/apollo-server-core/dist/runQuery.js:21:56
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

**Partial Resolution**
By running `yarn upgrade --latest` on the both the server and client I was able to get the app working; however, I still see the `Type "Node" is missing a "__resolveType" resolver.` warning.

**Describe the solution you'd like to see**
An updated tutorial

**Additional context**
node 8.12.0, yarn 1.12.3

**Comment by nikolasburk** [comment]
Hey @bwobst, thanks a lot for opening the issue. I just gave a major update to the boilerplates, so the fullstack React boilerplate should be working again. Please open another issue if you come across any other error! 🙏
